export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const FETCH_HOROSCOPE = 'FETCH_HOROSCOPE'
export const FETCH_HISTORY = 'FETCH_HISTORY'
export const FETCH_LOVED_SONGS = 'FETCH_LOVED_SONGS'
export const FETCH_SONG_DATA = 'FETCH_SONG_DATA'
export const FETCH_ARTIST_DATA = 'FETCH_ARTIST_DATA'
export const UPDATE_USER = 'UPDATE_USER'

